// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDatSan_UNETI5_DHTI17A4HN.Data;

#nullable disable

namespace QuanLyDatSan_UNETI5_DHTI17A4HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261002055301_KhoiTaoM1")]
    partial class KhoiTaoM1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDatSan_UNETI5_DHTI17A4HN.Models.LoaiSan", b =>
                {
                    b.Property<int>("MaLoaiSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiSan"));

                    b.Property<decimal>("DonGiaTheoGio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Vietnamese_100_CI_AS");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiSan");

                    b.HasIndex("TenLoai")
                        .IsUnique();

                    b.ToTable("LoaiSan", null, t =>
                        {
                            t.HasCheckConstraint("CK_LoaiSan_DonGiaTheoGio", "[DonGiaTheoGio] >= 0");

                            t.HasCheckConstraint("CK_LoaiSan_SoNguoiToiDa", "[SoNguoiToiDa] > 0");

                            t.HasCheckConstraint("CK_LoaiSan_TenLoai", "LEN(LTRIM(RTRIM([TenLoai]))) > 0");

                            t.HasCheckConstraint("CK_LoaiSan_TrangThai", "[TrangThai] IN (0, 1)");
                        });

                    b.HasData(
                        new
                        {
                            MaLoaiSan = 1,
                            DonGiaTheoGio = 200000m,
                            SoNguoiToiDa = 10,
                            TenLoai = "Bóng đá 5 người",
                            TrangThai = 1
                        },
                        new
                        {
                            MaLoaiSan = 2,
                            DonGiaTheoGio = 300000m,
                            SoNguoiToiDa = 14,
                            TenLoai = "Bóng đá 7 người",
                            TrangThai = 1
                        },
                        new
                        {
                            MaLoaiSan = 3,
                            DonGiaTheoGio = 80000m,
                            SoNguoiToiDa = 4,
                            TenLoai = "Cầu lông",
                            TrangThai = 1
                        },
                        new
                        {
                            MaLoaiSan = 4,
                            DonGiaTheoGio = 150000m,
                            SoNguoiToiDa = 10,
                            TenLoai = "Bóng rổ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaLoaiSan = 5,
                            DonGiaTheoGio = 120000m,
                            SoNguoiToiDa = 4,
                            TenLoai = "Quần vợt",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("QuanLyDatSan_UNETI5_DHTI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Vietnamese_100_CI_AS");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", null, t =>
                        {
                            t.HasCheckConstraint("CK_TaiKhoan_TenDangNhap", "LEN(LTRIM(RTRIM([TenDangNhap]))) > 0");

                            t.HasCheckConstraint("CK_TaiKhoan_TrangThai", "[TrangThai] IN (0, 1)");

                            t.HasCheckConstraint("CK_TaiKhoan_VaiTro", "[VaiTro] IN (1, 2, 3)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
